#
# (C) Copyright IBM Corp. 2019
#
FROM ubuntu:16.04

ARG uid=1000

# Install environment
RUN apt-get update -y && apt-get install -y \
	git \
	wget \
	python3.5 \
	python3-pip \
	python-setuptools \
	python3-nacl \
	apt-transport-https \
	ca-certificates \
	supervisor \
        net-tools \
        netcat \
        curl \
        telnet \
        nano \
        vim \
        nginx

RUN pip3 install -U \
	pip==9.0.3 \
	setuptools

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 68DB5E88
ARG indy_stream=master
RUN echo "deb https://repo.sovrin.org/deb xenial $indy_stream" >> /etc/apt/sources.list

RUN useradd -ms /bin/bash -u $uid indy

ARG indy_plenum_ver=1.9.1~dev856
ARG indy_node_ver=1.9.1~dev1043
ARG python3_indy_crypto_ver=0.4.5
ARG indy_crypto_ver=0.4.5

RUN apt-get update -y && apt-get install -y \
        python3-pyzmq=17.0.0 \
        indy-plenum=${indy_plenum_ver} \
        indy-plenum=${indy_plenum_ver} \
        indy-node=${indy_node_ver} \
        python3-indy-crypto=${python3_indy_crypto_ver} \
        libindy-crypto=${indy_crypto_ver} \
        vim

RUN echo "[supervisord]\n\
logfile = /tmp/supervisord.log\n\
logfile_maxbytes = 50MB\n\
logfile_backups=10\n\
logLevel = error\n\
pidfile = /tmp/supervisord.pid\n\
nodaemon = true\n\
minfds = 1024\n\
minprocs = 200\n\
umask = 022\n\
identifier = supervisor\n\
directory = /tmp\n\
nocleanup = true\n\
childlogdir = /tmp\n\
strip_ansi = false\n\
\n\
[program:node1]\n\
command=start_indy_node Node1 0.0.0.0 9711 0.0.0.0 9712\n\
directory=/home/indy\n\
stdout_logfile=/tmp/node1.log\n\
stderr_logfile=/tmp/node1.log\n\
user = indy\n\
\n\
[program:node2]\n\
command=start_indy_node Node2 0.0.0.0 9713 0.0.0.0 9714\n\
directory=/home/indy\n\
stdout_logfile=/tmp/node2.log\n\
stderr_logfile=/tmp/node2.log\n\
user = indy\n\
\n\
[program:node3]\n\
command=start_indy_node Node3 0.0.0.0 9715 0.0.0.0 9716\n\
directory=/home/indy\n\
stdout_logfile=/tmp/node3.log\n\
stderr_logfile=/tmp/node3.log\n\
user = indy\n\
\n\
[program:node4]\n\
command=start_indy_node Node4 0.0.0.0 9717 0.0.0.0 9718\n\
directory=/home/indy\n\
stdout_logfile=/tmp/node4.log\n\
stderr_logfile=/tmp/node4.log\n\
user = indy\n\
\n\
[program:fileservice]\n\
command=nginx -g 'daemon off;'\n\
stdout_logfile=/tmp/fileservice.log\n\
stderr_logfile=/tmp/fileservice.log\n"\
>> /etc/supervisord.conf

RUN awk '{if (index($1, "NETWORK_NAME") != 0) {print("NETWORK_NAME = \"sandbox\"")} else print($0)}' /etc/indy/indy_config.py> /tmp/indy_config.py
RUN mv /tmp/indy_config.py /etc/indy/indy_config.py
RUN echo "logLevel=0" >> /etc/indy/indy_config.py

COPY bin/* /home/indy/bin/
COPY nginx/ /etc/nginx

EXPOSE 9711 9712 9713 9714 9715 9716 9717 9718 8000

# USER indy

CMD ["/home/indy/bin/start-ledger"]
